const MILLISECONDS = 1;
const SECONDS = 1000 * MILLISECONDS;
const MINUTES = 60 * SECONDS;
const HOURS = 60 * MINUTES;
const DAY = 24 * HOURS;

export const DATE = {
	MILLISECONDS,
	SECONDS,
	MINUTES,
	HOURS,
	DAY,
};
